version: "3.7"

services:
  user-service:
    build:
      ./service/user/
  order-service:
    build:
      ./service/order/
  api-gateway:
    build:
      ./
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
    links:
      - "redis:redis"
      - "user-service:user-service"
      - "order-service:order-service"
  redis:
    image: redis:5.0.8
